name: SphereBattles
version: 1.0
api-version: 1.19
author: Refrizor
database: true
main: me.azzy.DiamondFire
description: Inferris SphereBattles

commands:
  checkrank:
    description: Debugging tool
  status:
    description: Debugging tool for DB
  test:
    description: Admin tool for generation
  setrank:
    description: Setrank
  fly:
    description: Flight
  shout:
    description: Shout
  admin:
    description: Admin in-game panel
  locationstick:
    description: Locaion stick
  setbadge:
    description: Set badge
  gamemaster:
    description: Game master
  ranks:
    description: Ranks
  nick:
    description: Nick
  adminv:
    description: Adminv
  patch:
    description: Patch
  spawn:
    description: Spawn command
  purgedata:
    description: Purge database tables
  config:
    description: Configuration command